
from flask import Flask, render_template, send_from_directory, abort
import os

app = Flask(__name__)

# ═══════════════════════════════════════════════════════════
# ARCHETYPE DATA — toate cele 12 arhetipuri
# ═══════════════════════════════════════════════════════════

ARCHETYPES = {
    'inocentul': {
        'num': '01',
        'name_ro': 'Inocentul',
        'name_en': 'The Innocent',
        'emoji': '🌱',
        'group_ro': 'Ego · Pregătire',
        'group_en': 'Ego · Preparation',
        'subtitle_ro': 'Cel care vede mereu partea plină a paharului',
        'subtitle_en': 'The one who always sees the glass half full',
        'color': '#87CEEB',
        'color2': '#FFD700',
        'desire_ro': 'Să fie fericit și în siguranță',
        'desire_en': 'To be happy and safe',
        'fear_ro': 'Să fie pedepsit pentru o greșeală',
        'fear_en': 'To be punished for doing something wrong',
        'motto': 'Free to be you and me',
        'slides': 13,
        'prev': None,
        'next': 'orfanul',
        'prev_name': None,
        'next_name': '🌿 Orfanul',
        'audio': 'inocentul.m4a',
        'key_quote_ro': 'Optimismul nu este naivitate. Este curajul de a crede în bine în ciuda evidenței.',
        'key_quote_en': 'Optimism is not naivety. It is the courage to believe in good despite the evidence.',
    },
    'orfanul': {
        'num': '02',
        'name_ro': 'Orfanul',
        'name_en': 'The Orphan',
        'emoji': '🌿',
        'group_ro': 'Ego · Pregătire',
        'group_en': 'Ego · Preparation',
        'subtitle_ro': 'Cel care caută conexiunea și apartenența',
        'subtitle_en': 'The one who seeks connection and belonging',
        'color': '#D2691E',
        'color2': '#F4A460',
        'desire_ro': 'Să aparțină, să fie conectat',
        'desire_en': 'To belong, to be connected',
        'fear_ro': 'Să fie abandonat sau exploatat',
        'fear_en': 'To be abandoned or exploited',
        'motto': 'All men and women are created equal',
        'slides': 11,
        'prev': 'inocentul',
        'next': 'razboinicul',
        'prev_name': '🌱 Inocentul',
        'next_name': '🦁 Războinicul',
        'audio': 'orfanul.m4a',
        'key_quote_ro': 'Vulnerabilitatea nu este slăbiciune. Este poarta prin care intră conexiunea autentică.',
        'key_quote_en': 'Vulnerability is not weakness. It is the gate through which authentic connection enters.',
    },
    'razboinicul': {
        'num': '03',
        'name_ro': 'Războinicul',
        'name_en': 'The Warrior',
        'emoji': '🦁',
        'group_ro': 'Ego · Pregătire',
        'group_en': 'Ego · Preparation',
        'subtitle_ro': 'Forța interioară a acțiunii disciplinate',
        'subtitle_en': 'The inner force of disciplined action',
        'color': '#8B4513',
        'color2': '#CD853F',
        'desire_ro': 'Să câștige și să dovedească valoarea',
        'desire_en': 'To win and prove worth',
        'fear_ro': 'Să pară slab sau vulnerabil',
        'fear_en': 'To appear weak or vulnerable',
        'motto': 'Where there\'s a will, there\'s a way',
        'slides': 10,
        'prev': 'orfanul',
        'next': 'protectorul',
        'prev_name': '🌿 Orfanul',
        'next_name': '🛡️ Protectorul',
        'audio': 'razboinicul.m4a',
        'key_quote_ro': 'Curajul nu este absența fricii. Este disciplina de a acționa în ciuda ei.',
        'key_quote_en': 'Courage is not the absence of fear. It is the discipline to act despite it.',
    },
    'protectorul': {
        'num': '04',
        'name_ro': 'Protectorul',
        'name_en': 'The Protector',
        'emoji': '🛡️',
        'group_ro': 'Ego · Pregătire',
        'group_en': 'Ego · Preparation',
        'subtitle_ro': 'Cel care oferă siguranță în viața de zi cu zi',
        'subtitle_en': 'The one who provides safety in everyday life',
        'color': '#556B2F',
        'color2': '#8FBC8F',
        'desire_ro': 'Să protejeze și să îngrijească',
        'desire_en': 'To protect and care for others',
        'fear_ro': 'Să vadă pe cineva drag suferind',
        'fear_en': 'To see someone dear suffering',
        'motto': 'Love your neighbour as yourself',
        'slides': 13,
        'prev': 'razboinicul',
        'next': 'exploratorul',
        'prev_name': '🦁 Războinicul',
        'next_name': '🚀 Exploratorul',
        'audio': 'protectorul.m4a',
        'key_quote_ro': 'A proteja nu înseamnă a controla. Înseamnă a crea spațiul în care ceilalți pot crește.',
        'key_quote_en': 'To protect is not to control. It means creating the space in which others can grow.',
    },
    'exploratorul': {
        'num': '05',
        'name_ro': 'Exploratorul',
        'name_en': 'The Explorer',
        'emoji': '🚀',
        'group_ro': 'Suflet · Călătoria',
        'group_en': 'Soul · The Journey',
        'subtitle_ro': 'Busola ta interioară spre autenticitate',
        'subtitle_en': 'Your inner compass toward authenticity',
        'color': '#8B6914',
        'color2': '#DAA520',
        'desire_ro': 'Libertatea de a afla cine ești cu adevărat',
        'desire_en': 'The freedom to discover who you truly are',
        'fear_ro': 'Conformismul, captivitatea, golul interior',
        'fear_en': 'Conformism, captivity, inner emptiness',
        'motto': 'Don\'t fence me in',
        'slides': 12,
        'prev': 'protectorul',
        'next': 'rebelul',
        'prev_name': '🛡️ Protectorul',
        'next_name': '⚡ Rebelul',
        'audio': 'exploratorul.m4a',
        'key_quote_ro': 'Nu mergi spre o destinație — urmărești ce este deja în tine.',
        'key_quote_en': 'You are not heading toward a destination — you are following what is already in you.',
    },
    'rebelul': {
        'num': '06',
        'name_ro': 'Rebelul',
        'name_en': 'The Rebel',
        'emoji': '⚡',
        'group_ro': 'Suflet · Călătoria',
        'group_en': 'Soul · The Journey',
        'subtitle_ro': 'Un ghid pentru spiritele libere',
        'subtitle_en': 'A guide for free spirits',
        'color': '#1a1a1a',
        'color2': '#FFD700',
        'desire_ro': 'Revoluția și distrugerea a ce nu mai funcționează',
        'desire_en': 'Revolution and destruction of what no longer works',
        'fear_ro': 'Să fie neputincios sau conformist',
        'fear_en': 'To be powerless or conformist',
        'motto': 'Rules are made to be broken',
        'slides': 11,
        'prev': 'exploratorul',
        'next': 'iubitorului',
        'prev_name': '🚀 Exploratorul',
        'next_name': '💫 Iubitorului',
        'audio': 'rebelul.m4a',
        'key_quote_ro': 'Revoluția autentică nu vine din ură. Vine din iubire — pentru ce ar putea fi.',
        'key_quote_en': 'Authentic revolution does not come from hate. It comes from love — for what could be.',
    },
    'iubitorului': {
        'num': '07',
        'name_ro': 'Iubitorului',
        'name_en': 'The Lover',
        'emoji': '💫',
        'group_ro': 'Suflet · Călătoria',
        'group_en': 'Soul · The Journey',
        'subtitle_ro': 'Anatomia conexiunii autentice',
        'subtitle_en': 'The anatomy of authentic connection',
        'color': '#8B0000',
        'color2': '#FF69B4',
        'desire_ro': 'Intimitate, conexiune și experiența frumuseții',
        'desire_en': 'Intimacy, connection and the experience of beauty',
        'fear_ro': 'Să fie singur și nedorit',
        'fear_en': 'To be alone and unwanted',
        'motto': 'You\'re the one I want',
        'slides': 13,
        'prev': 'rebelul',
        'next': 'creatorul',
        'prev_name': '⚡ Rebelul',
        'next_name': '🎨 Creatorul',
        'audio': 'iubitorului.m4a',
        'key_quote_ro': 'Pasiunea adevărată nu epuizează. Ea alimentează. Când iubești cu adevărat, devii mai mult.',
        'key_quote_en': 'True passion does not exhaust. It fuels. When you truly love, you become more.',
    },
    'creatorul': {
        'num': '08',
        'name_ro': 'Creatorul',
        'name_en': 'The Creator',
        'emoji': '🎨',
        'group_ro': 'Suflet · Călătoria',
        'group_en': 'Soul · The Journey',
        'subtitle_ro': 'Arhitectul propriei tale vieți',
        'subtitle_en': 'The architect of your own life',
        'color': '#FF6B35',
        'color2': '#F7C948',
        'desire_ro': 'Să creeze ceva cu valoare durabilă',
        'desire_en': 'To create something of enduring value',
        'fear_ro': 'Viziunea mediocră sau execuția slabă',
        'fear_en': 'Mediocre vision or poor execution',
        'motto': 'If you can imagine it, you can create it',
        'slides': 12,
        'prev': 'iubitorului',
        'next': 'magicianul',
        'prev_name': '💫 Iubitorului',
        'next_name': '✨ Magicianul',
        'audio': 'creatorul.m4a',
        'key_quote_ro': 'Nu construiești o casă. Construiești un vas pentru viața cuiva.',
        'key_quote_en': 'You are not building a house. You are building a vessel for someone\'s life.',
    },
    'magicianul': {
        'num': '09',
        'name_ro': 'Magicianul',
        'name_en': 'The Magician',
        'emoji': '✨',
        'group_ro': 'Sinele · Întoarcerea',
        'group_en': 'The Self · The Return',
        'subtitle_ro': 'Arhitectul transformării',
        'subtitle_en': 'The architect of transformation',
        'color': '#0a0a2e',
        'color2': '#C9A96E',
        'desire_ro': 'Să transforme viziunea în realitate prin cunoaștere',
        'desire_en': 'To transform vision into reality through knowledge',
        'fear_ro': 'Consecințe negative neintenționate',
        'fear_en': 'Unintended negative consequences',
        'motto': 'I am what I am',
        'slides': 12,
        'prev': 'creatorul',
        'next': 'inteleptul',
        'prev_name': '🎨 Creatorul',
        'next_name': '🔮 Înțeleptul',
        'audio': 'magicianul.m4a',
        'key_quote_ro': 'Eu transform viziunea în realitate prin înțelegere și claritate.',
        'key_quote_en': 'I transform vision into reality through understanding and clarity.',
    },
    'inteleptul': {
        'num': '10',
        'name_ro': 'Înțeleptul',
        'name_en': 'The Sage',
        'emoji': '🔮',
        'group_ro': 'Sinele · Întoarcerea',
        'group_en': 'The Self · The Return',
        'subtitle_ro': 'Vocea rațiunii și a cunoașterii din tine',
        'subtitle_en': 'The voice of reason and knowledge within you',
        'color': '#0d1b2e',
        'color2': '#C9A96E',
        'desire_ro': 'Descoperirea adevărului și înțelepciunea',
        'desire_en': 'The discovery of truth and wisdom',
        'fear_ro': 'Să fie indus în eroare sau să rămână ignorant',
        'fear_en': 'To be deceived or remain ignorant',
        'motto': 'The truth will set you free',
        'slides': 12,
        'prev': 'magicianul',
        'next': 'conducatorul',
        'prev_name': '✨ Magicianul',
        'next_name': '👑 Conducătorul',
        'audio': 'inteleptul.m4a',
        'key_quote_ro': 'Cunoașterea fără înțelepciune este periculoasă. Înțelepciunea fără compasiune este rece.',
        'key_quote_en': 'Knowledge without wisdom is dangerous. Wisdom without compassion is cold.',
    },
    'conducatorul': {
        'num': '11',
        'name_ro': 'Conducătorul',
        'name_en': 'The Ruler',
        'emoji': '👑',
        'group_ro': 'Sinele · Întoarcerea',
        'group_en': 'The Self · The Return',
        'subtitle_ro': 'Ordinea care naște libertatea',
        'subtitle_en': 'The order that births freedom',
        'color': '#1a0a0a',
        'color2': '#8B0000',
        'desire_ro': 'Controlul și ordinea pentru binele comun',
        'desire_en': 'Control and order for the common good',
        'fear_ro': 'Haosul și pierderea puterii',
        'fear_en': 'Chaos and loss of power',
        'motto': 'Power isn\'t everything, it\'s the only thing',
        'slides': 12,
        'prev': 'inteleptul',
        'next': 'bufonul',
        'prev_name': '🔮 Înțeleptul',
        'next_name': '🤡 Bufonul',
        'audio': 'conducatorul.m4a',
        'key_quote_ro': 'Liderul autentic nu conduce pentru a stăpâni. Conduce pentru a elibera potențialul celor din jur.',
        'key_quote_en': 'The authentic leader does not lead to rule. He leads to liberate the potential of those around him.',
    },
    'bufonul': {
        'num': '12',
        'name_ro': 'Bufonul',
        'name_en': 'The Jester',
        'emoji': '🤡',
        'group_ro': 'Sinele · Întoarcerea',
        'group_en': 'The Self · The Return',
        'subtitle_ro': 'Psihologia bucuriei, umorului și libertății interioare',
        'subtitle_en': 'The psychology of joy, humor and inner freedom',
        'color': '#FFB800',
        'color2': '#FF6B35',
        'desire_ro': 'Să trăiască clipa cu bucurie și autenticitate',
        'desire_en': 'To live the moment with joy and authenticity',
        'fear_ro': 'Să fie plictisit sau să îi plictisească pe alții',
        'fear_en': 'To be bored or to bore others',
        'motto': 'You only live once',
        'slides': 12,
        'prev': 'conducatorul',
        'next': None,
        'prev_name': '👑 Conducătorul',
        'next_name': None,
        'audio': 'bufonul.m4a',
        'key_quote_ro': 'Râsul este cel mai scurt drum între două suflete. Bufonul știe ce uită filozoful.',
        'key_quote_en': 'Laughter is the shortest distance between two souls. The Jester knows what the philosopher forgets.',
    },
}

ARCHETYPE_ORDER = ['inocentul','orfanul','razboinicul','protectorul','exploratorul',
                   'rebelul','iubitorului','creatorul','magicianul','inteleptul',
                   'conducatorul','bufonul']

# ═══════════════════════════════════════════════════════════
# ROUTES
# ═══════════════════════════════════════════════════════════

@app.route('/')
def index():
    return render_template('index.html', archetypes=ARCHETYPES, order=ARCHETYPE_ORDER)

@app.route('/arhetip/<slug>')
def arhetip(slug):
    if slug not in ARCHETYPES:
        abort(404)
    arch = ARCHETYPES[slug]
    slide_count = arch.get('slides', 12)
    slides = [f'/static/slides/{slug}/slide-{str(i).zfill(2)}.jpg' for i in range(1, slide_count + 1)]
    return render_template(f'arhetipuri/{slug}.html',
        arch=arch,
        slug=slug,
        slides=slides,
        archetypes=ARCHETYPES
    )

@app.route('/static/slides/<arch>/<filename>')
def serve_slide(arch, filename):
    slide_dir = os.path.join(app.root_path, 'static', 'slides', arch)
    return send_from_directory(slide_dir, filename)

@app.route('/static/audio/<filename>')
def serve_audio(filename):
    audio_dir = os.path.join(app.root_path, 'static', 'audio')
    return send_from_directory(audio_dir, filename, mimetype='audio/mpeg')

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5001))
    app.run(host='0.0.0.0', port=port, debug=False)
